apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      nodeName: ip-172-31-32-162.us-east-2.compute.internal
      containers:
        - name: my-springboot-app
          image: shefink/spring-boot-app
          ports: 
            - containerPort: 8050
          volumeMounts:
            - mountPath: /data
              name: springboot-storage
      volumes:
        - name: springboot-storage
          persistentVolumeClaim:
            claimName: springboot-pvc
# service file for Deployment       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    nodePort: 30001
    protocol: TCP
    targetPort: 8085
  type: NodePort
  selector:
    app: springboot-app

---
#Persistent Volume file
apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-pv
  labels:
    app: springboot-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mountpath"
---

#Persistent Volume Claim file

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-pvc
  labels:
    app: springboot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
